apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - prometheus.yaml
  - grafana.yaml
  - api-server.yaml
  - worker-agent.yaml
  - web-ui.yaml
  - ingress.yaml

namespace: solvyd
